[package]
name = "counter_program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.3.1"
borsh-derive = "1.3.1"
solana-program = "1.17.16"

[lib]
name = "counter_program"
crate-type = ["cdylib", "lib"]
